language: ruby
rvm:
- 2.1
install:
- bundle install --path vendor/bundle
- npm install
- sh -e /etc/init.d/xvfb start
- webdriver-manager update
script:
- bundle exec jekyll serve --detach
- npm test
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - DISPLAY=:99.0
branches:
  only:
  - gh-pages
cache:
  directories:
  - node_modules
  - vendor/bundle
