language: node_js
node_js:
- stable
install:
- rvm install 2.0
- rvm use 2.0
- gem install github-pages
- npm install
- sh -e /etc/init.d/xvfb start
- webdriver-manager update
script:
- jekyll serve --detach
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm test'
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - DISPLAY=:99.0
branches:
  only:
  - gh-pages
