language: ruby
rvm:
- 2.4
install:
- bundle install --jobs=3 --retry=3 --deployment
- npm install protractor
- sh -e /etc/init.d/xvfb start
- webdriver-manager update
script:
- bundle exec jekyll serve --detach
- npm test
- pkill -f jekyll
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - DISPLAY=:99.0
branches:
  only:
  - gh-pages
