language: ruby
rvm:
- 2.4
install:
- bundle install --jobs=3 --retry=3 --deployment
- npm install protractor
- sh -e /etc/init.d/xvfb start
- node_modules/.bin/webdriver-manager update
script:
- bundle exec jekyll serve --detach
- npm test
env:
  global:
  - DISPLAY=:99.0
branches:
  only:
  - gh-pages
